console.log(Math);
console.log(Math.PI);
console.log(Math.abs(-7.8));
console.log(Math.ceil(7.8));
console.log(Math.floor(7.8));
console.log(Math.round(7.8));
console.log(Math.sqrt(81));
console.log(Math.pow(2,5));
console.log(Math.sign(-6));
console.log(Math.random());
console.log(Math.random()*1000);
console.log(Math.round(Math.random() *  1000));